#title in header
title: "Hi Folks."

#main info
#owner
owner: "0x1om"
email: 1onkar@protonmail.com
info: "I dream of networks"
#description
desc: "Personal web log. Content may be read but not used for anything. Like a dream."
#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
#usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: svtntr
placelink: https://svtntr.com
github: https://github.com/1-om
##linkedin: https://linkedin.com/in/
twitter: https://twitter.com/0x1om
##instagram: https://instagram.com/
##stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: 
